info/__init__.py
from redis import StrictRedis
from flask import Flask
from flask_session import Session
#  导入flask_SQLAlchemy包与python交互
from flask_sqlalchemy import SQLAlchemy
#  导入配置对象
from config import config_dict

from config import Config
#  从flask-wtf中导入CSRFProtect，csrf
from flask_wtf import CSRFProtect,csrf
#  实例化数据库sqlalchemy
db = SQLAlchemy()


#   实例化redis数据库，用来存储与业务相关的数据，比如图形验证码、手机验证码,默认从redis中拿出来的响应数据为bites类型
redis_store = StrictRedis(host=Config.REDIS_HOST,port=Config.REDIS_PORT,decode_responses=True)

#  导入日志模块
import logging
from logging.handlers import RotatingFileHandler

# 设置日志的记录等级
logging.basicConfig(level=logging.DEBUG) # 调试debug级
# 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024*1024*100, backupCount=10)
# 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
# 为刚创建的日志记录器设置日志记录格式
file_log_handler.setFormatter(formatter)
# 为全局的日志工具对象（flask app使用的）添加日志记录器
logging.getLogger().addHandler(file_log_handler)

#  定义工厂函数，生产app，可以改变代码执行顺序
#  动态的修改程序的配置



def create_app(config_name):
    #  实例化app
    app = Flask(__name__)
    app.config.from_object(config_dict[config_name])
    
    #  实例化csrfprotect对象
    CSRFProtect(app)
    #  利用请求钩子，在每一次请求结束后通过响应给response给前端浏览器写入带有cookie的带有csrf的保护令牌
    @app.after_request
    def after_request(response):
        csrf_token = csrf.generate_csrf()
        response.set_cookie('csrf_token',csrf_token)
        return response

    
    #  让session扩展和程序实例关联起来
    Session(app)
    db.init_app(app)

    #  注册蓝图
    from info.modules.news import news_blue
    app.register_blueprint(news_blue)
    from info.modules.passport import passport_blue
    app.register_blueprint(passport_blue)
    from info.modules.profile import profile_blue
    app.register_blueprint(profile_blue)


    #  导入自定义的过滤器
    from info.utils.commons import index_filter
    #  将自定义的过滤器加入到程序实例内置的过滤器中
    app.add_template_filter(index_filter,'index_filter')
    
    return app

info/modules/news/__init__.py
from flask import Blueprint

#  创建蓝图对象

news_blue = Blueprint('news_blue',__name__)

from . import views

info/modules/news/views.py
from flask import render_template,current_app, jsonify,g,request
from info.utils.response_code import RET
from info.models import Category,News
from . import news_blue
from info import constants,db
from info.utils.commons import login_required


#  项目图标的加载
"""
    网站favicon图标的加载：
    1、浏览器自动加载，默认会访问的url，以获取图标：http://127.0.0.1:5000/favicon.ico
    2、定义路由，route('/favicon.ico'),实现把文件发送给浏览器，找到static/news/favicon.ico文件的路径。

    代码实现后，浏览器无法获取favicon图标的解决办法：
    1、清除浏览器浏览记录
    2、清除浏览器缓存
    3、彻底退出浏览器，重新启动。

    原因：因为浏览器加载favicon不是每次请求都加载。


"""
@news_blue.route('/favicon.ico')
def favicon():

    return current_app.send_static_file('news/favicon.ico')




#  项目首页的加载
# 一、 用户请求首页时查询数据库，将用户的需求渲染到模板首页
#  把新闻分类渲染到模板中

@news_blue.route('/')
@login_required
def index():

    #  通过检查用户登录状态装饰器的请求对象g来实例化用户user
    user = g.user
    # 二、加载新闻分类
    # 1、查询新闻分类数据，mysql
    # ca = Category.query.all()
    # 2、判断查询结果是否有数据
    # 3、如果有数据，遍历查询结果，调用模型类中的to_dict函数
    # 4、返回新闻分类数据

    try:
        categories = Category.query.all()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR,errmsg='查询分类数据失败')
    if not categories:
        return jsonify(errno=RET.NODATA,errmsg='无新闻分类数据')
     # 遍历查询结果，调用模型类中的to_dict函数，获取字典数据
    category_list = []
    for category in categories:
        category_list.append(category.to_dict())

    # 三、加载新闻点击排行数据
    # 1、查询新闻点击排行数据，mysql
    # 2、根据新闻点击次数添加查询条件, News，order_by, desc, limit(6)
    # 3、判断查询结果
    # 4、遍历查询结果，调用模型类中的to_dict函数
    # 5、返回新闻排行数据

    # 查询新闻点击排行数据，mysql,实例化news新闻对象
    try:
        news_rank = News.query.order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR,errmsg='查询新闻排行数据失败')
    if not news_rank:
        return jsonify(errno=RET.NODATA,errmsg='无新闻点击排行数据')
    #  定义一个点击排行的列表，用来存放点击排行新闻
    news_rank_list = []
    for news in news_rank:
        news_rank_list.append(news.to_dict())



    # 定义字典，给模板传入用户数据
    #  使用三元运算符判断查询结果
    data = {
        'user_info':user.to_dict() if user else None,
        'category_list':category_list,
        'news_rank_list':news_rank_list
    }


    return render_template('news/index.html',data= data)



#  新闻列表数据
@news_blue.route('/news_list')
def news_list():
    #  获取参数---检查参数---业务处理---返回结果
    """1、获取参数
    cid，page，per_page,需要给默认值
    2、检查参数，转换参数的数据类型
    3、根据分类id查询指定分类下的新闻数据，按照新闻的发布时间倒叙排序，并且进行分页
        实现形式一：写多条查询语句
        if cid == 1:如果是最新，查询所有新闻，过滤条件为空
            News.query.filter().order_by(News.create_time.desc()).paginate(page,per_page,False)
        else:
            如果选择了不是'最新'的分类,根据分类id进行查询新闻数据
            News.query.filter(News.category_id==cid).order_by(News.create_time.desc()).paginate(page,per_page,False)
        实现形式二：写一条查询语句
        filters = []
        if cid > 1:如果不是最新，添加分类id
            filters.append(News.category_id==cid)
        News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page,per_page,False)
    4、获取分页后的数据，总数据items、当前页数page、总页数pages
    5、遍历总数据，调用模型类中的to_dict函数，获取新闻的字典数据
    6、返回结果
        总数据items、当前页数page、总页数pages"""
    #  获取参数cid，page，per_page,需要给默认值
    cid = request.args.get('cid','1')
    page = request.args.get('page','1')
    per_page = request.args.get('per_page','10')

    #  检查参数，转换参数的数据类型
    try:
        cid,page,per_page = int(cid),int(page),int(per_page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno= RET.PARAMERR,errmsg='参数缺失')

    #  根据分类id查询指定分类下的新闻数据，按照新闻的发布时间倒叙排序，并且进行分页
    filters = []
    if cid > 1:
        filters.append(News.category_id == cid)
    try:
        paginate = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page,per_page,False)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR,errmsg='查询新闻列表数据失败')
    #  获取分页后的数据，数据items、当前页数page、总页数pages
    news_list = paginate.items
    current_page = paginate.page
    total_page = paginate.pages

    #  定义新闻列表，循环遍历渲染到模板到中
    news_dict_list = []
    for news in news_list:
        news_dict_list.append(news.to_dict())

    #  获取新闻的字典数据,返回前端模板数据
    data = {
        'news_dict_list':news_dict_list,
        'current_page':current_page,
        'total_page':total_page
    }

    #  返回结果

    return jsonify(errno=RET.OK, errmsg='OK', data=data)




#  新闻详情页的加载渲染
@news_blue.route('/<int:news_id>')
@login_required
def news_detail(news_id):
    """
    新闻详情页面
    1、使用模板展示数据，用户数据、点击排行，首页已经实现，直接复制过来
    2、url中传入新闻id，直接根据新闻id查询新闻的详情信息
    3、判断查询结果
    4、新闻点击次数加1，提交数据到mysql
    5、如果查询到新闻数据，调用模型类中to_dict函数

    :param news_id:
    :return:
    """
    user = g.user

    #  渲染新闻点击排行内容
    try:
        news_rank = News.query.order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='查询新闻排行数据失败')
    if not news_rank:
        return jsonify(errno=RET.NODATA, errmsg='无新闻点击排行数据')
        #  定义一个点击排行的列表，用来存放点击排行新闻
    news_rank_list = []
    for news in news_rank:
        news_rank_list.append(news.to_dict())


    #  新闻详情数据加载
    #  按照新闻id在mysql数据库中查询新闻news

    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='查询新闻详情数据失败')
    if not news:
        return jsonify(errno=RET.NODATA,errmsg='无新闻详情数据')

    # 新闻点击次数加1，提交数据到mysql
    news.clicks += 1
    # 保存新闻点击次数数据到mysql
    try:
        db.session.add(news)
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg='保存数据失败')


    #  用户收藏新闻和取消收藏的状态变换
    # 定义变量，用来标记收藏还是取消收藏
    is_collected = False
    #   判断用户是否已经登陆收藏，如果已收藏，则该标签改为相反值
    if user and (news in user.collection_news):
        is_collected = True













    data = {
        'user_info': user.to_dict() if user else None,
        'news_rank_list': news_rank_list,
        'news_detail': news.to_dict(),    # 如果查询到新闻数据，调用模型类中to_dict函数
        'is_collected':is_collected
    }


    return render_template('news/detail.html',data=data)




#   实现收藏和取消收藏的功能接口
@news_blue.route('/news_collect',methods=['POST'])
@login_required
def news_collect():
    """
        收藏和取消收藏
        获取参数---检查参数---业务处理---返回结果
        1、使用g对象尝试获取用户信息，如果用户未登录，直接返回错误信息，提示用户登录
        2、获取参数，news_id,action[collect,cancel_collect]
        3、检查参数的完整性
        4、转换新闻id的数据类型
        5、检查action参数的范围
        6、根据新闻id查询数据库，确认新闻的存在
        7、判断用户选择的是收藏或取消收藏
        收藏：user.collection_news.append(news) 用户未收藏过！！！
        取消：user.collection_news.remove(news)
        8、提交数据
        9、返回结果

        :return:
        """
    #  使用g对象尝试获取用户信息，如果用户未登录，直接返回错误信息，提示用户登录
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR, errmsg='用户未登录')

    #  获取参数，news_id,action[collect,cancel_collect]
    news_id = request.json.get('news_id')
    action = request.json.get('action')
    #  验证参数的完整性
    if not all([news_id,action]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数错误')
    #  转换新闻id的数据类型
    try:
        news_id = int(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.PARAMERR, errmsg='参数类型错误')
    #  检查action参数的范围
    if action not in ['collect', 'cancel_collect']:
        return jsonify(errno=RET.PARAMERR, errmsg='参数范围错误')
    #  根据新闻id查询数据库，确认新闻的存在
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg='查询新闻数据失败')
    if not news:
        return jsonify(errno=RET.NODATA, errmsg='无新闻数据')

    #  判断用户选择的是收藏或取消收藏
    #  收藏：user.collection_news.append(news) 用户未收藏过！！！
    #  取消：user.collection_news.remove(news)
    if action == 'collect':
        if news not in user.collection_news:
            user.collection_news.append(news)
    else:
        user.collection_news.remove(news)
     #  提交数据
    try:
         db.session.add(user)
         db.session.commit()
    except Exception as e:
         current_app.logger.error(e)
         db.session.rollback()
         return jsonify(errno=RET.DBERR, errmsg='保存数据失败')
    # 返回结果
    return jsonify(errno=RET.OK, errmsg='OK')

info/modules/passport/__init__.py
from flask import Blueprint

passport_blue = Blueprint('passport_blue',__name__)

from . import views

info/modules/profile/__init__.py
from flask import Blueprint

profile_blue = Blueprint('profile_blue',__name__,url_prefix='/user')

from . import views

info/modules/profile/views.py
from . import profile_blue
from info.utils.commons import login_required

from flask import g,render_template,redirect,request
@profile_blue.route('/info')
@login_required
def user_info():
    """
    用户基本信息显示
    1、尝试获取用户信息
    2、如果用户未登录，重定向到项目首页
    3、如果用户已登录，调用模型类中的to_dict函数，获取用户信息
    4、传给模板

    :return:
    """
    user = g.user
    if not user:
        return redirect('/')


    data = {
        'user':user.to_dict()

    }






    return render_template('news/user.html',data= data)

#  创建iframe子网页
#  基本资料
@profile_blue.route('/base_info',methods=['GET','POST'])
@login_required
def base_info():
    user = g.user
    if request.method == 'GET':
        data = {
            'user': user.to_dict()
        }
        return render_template('news/user_base_info.html', data=data)









#  头像设置
@profile_blue.route('/pic_info',methods=['GET','POST'])
@login_required
def pic_info():




   return render_template('news/user_pic_info.html')








#  我的关注
@profile_blue.route('/user_follow',methods=['GET','POST'])
@login_required
def user_follow():



   return render_template('news/user_follow.html')





#  密码修改
@profile_blue.route('/pass_info',methods=['GET','POST'])
@login_required
def pass_info():



   return render_template('news/user_pass_info.html')




#  我的收藏
@profile_blue.route('/collection',methods=['GET','POST'])
@login_required
def collection():



   return render_template('news/user_collection.html')


#   新闻发布
@profile_blue.route('/news_release',methods=['GET','POST'])
@login_required
def news_release():



   return render_template('news/user_news_release.html')





#  新闻列表
@profile_blue.route('/news_list',methods=['GET','POST'])
@login_required
def news_list():



   return render_template('news/user_news_list.html')

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
    {% block jsblock%}

    {% endblock %}

</head>
<body>
    <div class="header_con">
        <div class="header">
            <a href="#" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>

            <ul class="menu fl">
            {% block categoryblock %}

            {% endblock %}

            </ul>

            <!-- 用户登录后显示下面，隐藏上面 -->
            {% if data.user_info %}
                <div class="user_login fr">
                    <img src="{% if data.user_info.avatar_url %}{{ data.user_info.avatar_url }}{% else %}../../static/news/images/person01.png{% endif %}" class="lgin_pic">
                    <a href="#">{{ data.user_info.nick_name }}</a>
                    <a href="javascript:;" onclick="logout()">退出</a>
                </div>
            {% else %}
                <div class="user_btns fr">
                    <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
                </div>
            {% endif %}
        </div>
    </div>

    <div class="conter_con">
       {% block contentblock %}

       {% endblock %}
        <div class="rank_con fr">
        {% block authorblock %}

        {% endblock %}
            <div class="rank_title">
                <h3>点击排行</h3>
            </div>
            <ul class="rank_list">
                {% for news in data.news_rank_list %}
                    {# 过滤器的使用：自定义过滤器，实现动态的返回first、sencond、third #}
                    <li><span class="{{ loop.index0 | index_filter }}">{{ loop.index }}</span><a href="#">{{ news.title }}</a></li>

{#                <li><span class="first">1</span><a href="#">势如破竹！人民币再度连闯四道关口 在岸、离岸双双升破6.42</a></li>#}
{#                <li><span class="second">2</span><a href="#">凛冬已至，还有多少银行人在假装干银行</a></li>#}
{#                <li><span class="third">3</span><a href="#">人民日报：部分城市楼市放松限制引关注，楼市调控不会“拉抽屉”</a></li>#}
{#                <li><span>4</span><a href="#">势如破竹！人民币再度连闯四道关口 在岸、离岸双双升破6.42</a></li>#}
{#                <li><span>5</span><a href="#">凛冬已至，还有多少银行人在假装干银行</a></li>#}
{#                <li><span>6</span><a href="#">人民日报：部分城市楼市放松限制引关注，楼市调控不会“拉抽屉”</a></li>#}
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="footer">
        <div class="footer_links">
            <a href="">关于我们</a>
            <span>|</span>
            <a href="">联系我们</a>
            <span>|</span>
            <a href="">招聘人才</a>
            <span>|</span>
            <a href="">友情链接</a>
        </div>
        <p class="copyright">
            CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
电话：010-****888    京ICP备*******8号
        </p>
    </div>

    <!-- 登录表单 -->
    <form class="login_form_con">
        <div class="login_form">
            <div class="login_title">
                <h3>登 录</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input id="mobile" type="text" name="mobile" autocomplete="off">
                <div class="input_tip">手机号</div>
                <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input id="password" type="password" name="password">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="login-password-err" class="error_tip">密码不能为空</div>
            </div>
            <input type="submit" name="" value="登 录" class="input_sub">
            <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
        </div>
        <div class="mask"></div>
    </form>

    <!-- 注册表单 -->
    <form class="register_form_con">
        <div class="register_form">
            <div class="register_title">
                <h3>注 册</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
                <div class="input_tip">手机号</div>
                <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
                <div class="input_tip">图形验证码</div>
                <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
                <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="smscode" id="smscode" class="code_pwd">
                <div class="input_tip">手机验证码</div>
                <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
                <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
            </div>
            <div class="form_group">
                <input type="password" name="password" id="register_password" class="pass_input">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="register-password-err" class="error_tip">密码不能为空</div>
            </div>
            <div  class="form_group2 clearfix">
                <input type="checkbox" class="agree_input" checked>
                <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
                <div class="error_tip">请勾选</div>
            </div>
            <input type="submit" name="" value="注 册" class="input_sub">
            <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
        </div>
        <div class="mask"></div>
    </form>
</body>
</html>

info/templates/news/index.html
{% extends 'news/base.html' %}
{% block titleBlock %}首页-新经资讯{% endblock %}
{% block jsblock%}
    <script type="text/javascript" src="../../static/news/js/index.js"></script>
{% endblock %}

{% block categoryblock %}
    {% for category in data.category_list %}
        <li class="{% if loop.index0 == 0 %}active{% endif %}" data-cid="{{ category.id }}"><a href="javascript:;">{{ category.name }}</a></li>
    {% endfor %}
{% endblock %}

{% block contentblock %}
       <ul class="list_con fl">

       </ul>
{% endblock %}



    

info/templates/news/user.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户中心</title>
	<link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
	<link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
	<script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>
	<script type="text/javascript" src="../../static/news/js/main.js"></script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>

            {% if data.user %}
            <div class="user_login fr" style="display: block;">
				 <img src={% if data.user.avatar_url %} {{ data.user.avatar_url }}{% else %}"../../static/news/images/person01.png"{% endif %} class="lgin_pic">
                <a href="/user/info" id="nick_name">{{ data.user.nick_name }}</a>
				<a href="javascript:;" onclick="logout()">退出</a>
			</div>
            {% endif %}

		</div>
	</div>
	
	<div class="conter_con">
		<div class="user_menu_con fl">
			<div class="user_center_pic">
				 <img src="{% if data.user.avatar_url %}{{ data.user.avatar_url }}{% else %}../../static/news/images/user_pic.png{% endif %}" alt="用户图片" class="now_user_pic">

			</div>
			<div class="user_center_name">{{ data.user.nick_name }}</div>

			<ul class="option_list">
{#				<li class="active"><a href="/user/base_info" target="main_frame">基本资料</a></li>#}
				<li class="active"><a href="{{ url_for("profile_blue.base_info") }}" target="main_frame">基本资料</a></li>

                <li><a href="/user/pic_info" target="main_frame">头像设置</a></li>
				<li><a href="/user/user_follow" target="main_frame">我的关注</a></li>
				<li><a href="/user/pass_info" target="main_frame">密码修改</a></li>
				<li><a href="/user/collection" target="main_frame">我的收藏</a></li>
				<li><a href="/user/news_release" target="main_frame">新闻发布</a></li>
				<li><a href="/user/news_list" target="main_frame">新闻列表</a></li>
			</ul>
		</div>

		<div class="user_con fr">
			<iframe src="{{ url_for("profile_blue.base_info") }}" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>
		</div>		
	</div>
	<div class="footer">		
		<div class="footer_links">
			<a href="">关于我们</a>
			<span>|</span>
			<a href="">联系我们</a>
			<span>|</span>
			<a href="">招聘人才</a>
			<span>|</span>
			<a href="">友情链接</a>
		</div>
		<p class="copyright">
			CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
电话：010-****888    京ICP备*******8号
		</p>
	</div>
	
	<!-- 登录表单 -->
	<form class="login_form_con">
		<div class="login_form">
			<div class="login_title">
				<h3>登 录</h3>
				<a href="javascript:;" class="shutoff"></a>
			</div>
			<div class="form_group">				
				<input type="text" name="username" autocomplete="off">
				<div class="input_tip">用户名/手机号</div>
			</div>
			<div class="form_group">				
				<input type="password" name="password">
				<div class="input_tip">密码(不少于6位)</div>
			</div>
			<input type="submit" name="" value="登 录" class="input_sub">
			<div class="down_link">还没有账号？<a href="#" class="to_register">立即注册</a></div>
		</div>
		<div class="mask"></div>
	</form>
	
	<!-- 注册表单 -->
	<form class="register_form_con">
		<div class="register_form">
			<div class="register_title">
				<h3>注 册</h3>
				<a href="javascript:;" class="shutoff"></a>
			</div>
			<div class="form_group">				
				<input type="text" name="username" autocomplete="off" class="phone_input">
				<div class="input_tip">手机号</div>
				<div class="error_tip">手机号不能为空</div>
			</div>
			<div class="form_group">				
				<input type="password" name="code_pwd" class="code_pwd">
				<div class="input_tip">手机验证码</div>
				<a href="javascript:;" class="get_code">点击获取验证码</a>
				<div class="error_tip">验证码不能为空</div>
			</div>
			<div class="form_group">				
				<input type="password" name="password" class="pass_input">
				<div class="input_tip">密码(不少于6位)</div>
				<div class="error_tip">密码不能为空</div>
			</div>
			<div class="form_group">				
				<input type="password" name="code_pwd" class="code_pwd">
				<div class="input_tip">图形验证码</div>
				<img src="../../static/news/images/pic_code.png" class="get_pic_code">
				<div class="error_tip">图形码不能为空</div>
			</div>
			
			<div  class="form_group2 clearfix">
				<input type="checkbox" class="agree_input" checked>
				<p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
				<div class="error_tip">请勾选</div>
			</div>
			<input type="submit" name="" value="注 册" class="input_sub">
			<div class="down_link">已有账号？<a href="#" class="to_login">立即登录</a></div>
		</div>
		<div class="mask"></div>
	</form>
</body>
</html>

info/templates/news/user_collection.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户中心</title>
	<link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/jquery.pagination.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="../../static/news/js/jquery.pagination.min.js"></script>
</head>
<body class="inframe_body">
    <div class="my_collect">
        <h3>我的收藏</h3>
        <ul class="article_list">

            {% for news in data.collections %}
                <li><a href="/{{ news.id }}" target="_blank">{{ news.title }}</a><span>{{ news.create_time }}</span></li>
            {% endfor %}
        </ul>



        <div id="pagination" class="page"></div>
        <script>
            $(function() {
                $("#pagination").pagination({
                    currentPage: {{ data.current_page }},
                    totalPage: {{ data.total_page }},
                    callback: function(current) {
                        window.location.href = "/user/collection?p=" + current
                    }
                });
            });
        </script>

    </div>
</body>
</html>